name: ci

on:
  push:
    branches:
      - CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: taking PHP image
        image: php:7.1
        

      - name: Downloading commands
        run: apt-get update && apt-get install -y \ 
                  tar \
                  sudo \
                  git \
                  curl \ 
                  nano \
                  unzip \
                  wget \
                  vim \
                  net-tools \
                  libmagickwand-dev; \
                pecl install imagick; \
                docker-php-ext-enable imagick;

      - name: taking PHP image
        uses: 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          load: true
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest


# name: Docker CI

# on:
#   push:
#     branches:
#       - CI
#   # pull_request:
#   #   branches:
#   #     - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: php image pull 

#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Build Docker image
#         run: docker build . -t utsav0077/gymie:1.0

#       - name: Push Docker image
#         run: |
#           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#           docker push utsav0077/gymie:1.0