version : "3.0"
services:
  app:  
    #build: . 
    image: pro1:1.0
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db 
      DB_PORT: "3306"
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: "secret"
    ports: 
      - "8000:8000"
    depends_on:
      - db
    command:  
      - /bin/bash
      - -c
      - |  
        php artisan migrate &&
        php artisan serve --host=0.0.0.0 --port=8000 
    
  db:
    image: mysql:latest
    restart: always
    environment:
     MYSQL_DATABASE: homestead
     MYSQL_USER: homestead
     MYSQL_PASSWORD: secret   
     MYSQL_ROOT_PASSWORD : 123456  
    ports: 
     - '3306:3306'
    expose:
      - '3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql


volumes:
     db_data:
  
    