apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: project
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  
  resources:
    requests:
      storage: 1Gi
