apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}   
spec:
  selector:
    matchLabels:
      app: myapp-app
  replicas: {{ .Values.deployment.replicas}}
  template:
    metadata:
      labels:
        app: myapp-app  
    spec:
      containers:
      - name: {{ .Values.deployment.containers.name}}
        image: {{ .Values.deployment.containers.image.name}} 
        ports:
        - containerPort: {{ .Values.deployment.containers.ports.containerPort}}
          name: {{ .Values.deployment.containers.ports.name}}
        env: 
          - name: DB_CONNECTION
            valueFrom:
                configMapKeyRef:
                    name: app-config
                    key: DB_CONNECTION

          - name: DB_HOST
            valueFrom:
                configMapKeyRef:
                    name: app-config
                    key: DB_HOST

          - name: DB_PORT
            valueFrom:
                configMapKeyRef:
                    name: app-config
                    key: PORT

          - name: DB_DATABASE
            valueFrom:
                configMapKeyRef:
                    name: app-config
                    key: DB-US

          - name: DB_USERNAME
            valueFrom:
                configMapKeyRef:
                    name: app-config
                    key: DB-US

          - name: DB_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: DB_PASSWORD